### ISSUE TITLE
Tagging a JSON schema?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#10]
Is there a standard way in JSON Schema to signal to clients/parsers that a schema conforms to a specification (like JSON-FG, GeoJSON, etc. or an application profile)? Probably not, but it could make sense to establish a convention for JSON-FG profiles from the beginning so that schema-aware parsers can rely on it.

The discussion started in https://github.com/opengeospatial/ogcapi-features/issues/600.

**Comment by m-mohr** [comment]
Sounds a bit like the $schema keyword, but is not exactly what you are looking for, I think:
https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.8.1.1

**Comment by cportele** [comment]
Thanks, @m-mohr. In a JSON schema, the "$schema" member is for the JSON Schema dialect/version, AFAIK. This is a different purpose and value range.

I think we should first look around to see, if there is a pattern that others are already using.

**Comment by cportele** [comment]
Meeting 2021-07-12: We agreed that it is important that readers can determine which standards/specifications a schema conforms to. Potentially we could reference in the GeoJSON case the official GeoJSON schemas, but there are two issues:

* The GeoJSON schemas are in draft 07 and that creates issues with many implementations that mix schemas with other schema versions.
* The status and persistence of the GeoJSON schemas is unclear.

We could contact the GeoJSON maintainers about these issues, if we think that would address the problem.

On the use of "$schema", it was mentioned that we could still consider it, giving it our specific meaning in the JSON-FG context. This is a bit unclear, because JSON Schema defines the "$schema" member to identify the meta-schema. In any case, it would not identify the specifications that a JSON instance conforms to.

One option could be to have multiple "describedby" links, e.g. one to https://geojson.org/schema/FeatureCollection.json and one to the dataset-specific schema. @cportele will update the proposal and add an example.

**Comment by cportele** [comment]
The current draft supports multiple schema links. Another option, mentioned in a comment in the draft, is document level metadata / header with this information.

**Comment by cportele** [comment]
Meeting 2022-11-14:

* The original topic seems to heavily overlap with #70 and can be discussed in that issue.
* Links can be used in general to link to metadata.
* If there is a need for embedding additional metadata in JSON-FG documents we would need a clearer idea about the benefits of such members.

So, we can close this issue.
