### ISSUE TITLE
Question about coordRefSys and compound-CRS

### ISSUE THREAD

**Issue by jratike80** [opengeospatial/ogc-feat-geo-json#102]
I am not sure if this is the right repository to ask, but is it possible to define in coordRefSys a compound CRS that does not have an EPSG code? I speak only about Spatial compound coordinate reference systems (vertical + height) without complexity of time.

For example `ETRS89 / TM35FIN(N,E) + N2000 height` has a code `EPSG:3903`
but a similar `ETRS89 / TM35FIN(E,N) + N2000 height` does not have a code.
The Proj library recognizes compound CRS from concatenated codes, as for the latter example
`EPSG:3067+3900`

The standard https://docs.ogc.org/as/18-005r4/18-005r4.html#36 supports compound crs.

The discussion about crs-compound in https://github.com/opengeospatial/architecture-dwg/issues/29 may be related.

The question in this issue is related https://github.com/opengeospatial/ogcapi-features/issues/357

**Comment by cportele** [comment]
Compounds CRSs where each component CRS has a URI can be specified. 

Example using CURIEs: `"coordRefSys": ["[EPSG:3067]", "[EPSG:3900]"]`.

See https://docs.ogc.org/DRAFTS/21-045.html#_reference_system_values.

**Comment by jratike80** [comment]
How about OGCFeat? Is it possible to announce EPSG:3067+3900 as a storageCrs? What would be the syntax if plain EPSG:3067 is expressed as
` "storageCrs" : "http://www.opengis.net/def/crs/EPSG/0/3067"`?

**Comment by jratike80** [comment]
Would you mind to create an enhancement issue for Part 2? I am not lazy but I feel that you know better what to write into the description.

**Comment by cportele** [comment]
Done, see https://github.com/opengeospatial/ogcapi-features/issues/864. I am closing the issue here.
