### ISSUE TITLE
Update JSON-FG schemas at https://beta.schemas.opengis.net/json-fg/

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#120]
@ghobona 

Now that v0.2.2 is released, the schemas at https://beta.schemas.opengis.net/json-fg/ should be updated to reflect that latest draft version. 

The current content of the directory should be replaced by the content in the v0.2.2 schemas at  https://github.com/opengeospatial/ogc-feat-geo-json/releases/download/v0.2.2/json-fg-schemas-0.2.2.zip.

**Comment by cportele** [comment]
@ghobona - Is there an update on the status? Thanks!

**Comment by ghobona** [comment]
@kstegemoller will re-publish the schemas and then let the Communications team know so that they can proceed with announcing the Public Comment period.

**Comment by cportele** [comment]
Thanks @ghobona

**Comment by ogcportal** [comment]
JSON-FG 0.2.2 schemas are now hosted on https://beta.schemas.opengis.net/json-fg/ .

**Comment by cportele** [comment]
Thank you @ogcportal
