### ISSUE TITLE
Proposal: Encoding a spatial geometry

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#13]
Features typically have a spatial geometry that provides information about the location of the feature.

In GeoJSON, this information is encoded in the top-level "geometry" member. Supported are geometries according to the Simple Features standard (2D or 2.5D points, line strings, polygons or aggregations of them) in WGS 84 as the coordinate reference system (OGC:CRS84 or OGC:CRS84h).

It is a key motivation for JSON-FG to support additional requirements, including other coordinate reference systems as well as solids, where the boundary is specified using polygons.

To avoid confusing GeoJSON readers, such geometries will be provided in a new top-level member with the key "where" (or another name).

https://github.com/opengeospatial/ogc-feat-geo-json/blob/main/proposals/spatial-geometry.adoc

**Comment by cportele** [comment]
Meeting 2021-07-26: 

* Do we try to fall back to GeoJSON whenever possible (use "geometry" whenever we can and only require the use of "where", if the geometry cannot be represented as a GeoJSON geometry) or do we have a clean JSON-FG approach and simply allow generators to populate GeoJSON fallback content (potentially simplified)? In general, there is a tendency towards the first option. So, the current approach on v0.1.0 can stay as it is.
* Maybe we need information in a 'header' how a client should parse the content, in particular, if the data is parsed as a file, not as an API response with a content type header. Maybe Testbed 17 can look into this and test with the clients.
* Should we support that we can use a JSON Pointer in "where", if "where" and "geometry" are the same geometry? 
* Should we support multiple geometries per feature and clarifying the semantics of the geometry? The latter could potentially be addressed using JSON-LD contexts. Part 1 should continue to focus on the (minimal) extensions in the current charter. We need to do our best to avoid block future extensions.
* With respect to "extruded polygons" it seems like there could be useful, but it is unclear if the added complexity of an additional geometry is valuable enough. It is a general topic how to handle geometries that are constructed using regular feature properties.

**Comment by cportele** [comment]
November Code Sprint:

By default, an API should omit the `geometry` member, if the `where` member is provided.

If clients want to request the JSON-FG from an API with the fallback GeoJSON geometry (because the plan is to pass the document to others, e.g. make it available online as a static file), use a media type parameter `compatibility=geojson`. 

For example, compare:

* `curl "https://demo.ldproxy.net/zoomstack/collections/airports/items?limit=100&crs=http://www.opengis.net/def/crs/EPSG/0/27700" -H "Accept: application/vnd.ogc.fg+json"` ([link](https://demo.ldproxy.net/zoomstack/collections/airports/items?limit=100&crs=http://www.opengis.net/def/crs/EPSG/0/27700&f=jsonfg))
* `curl "https://demo.ldproxy.net/zoomstack/collections/airports/items?limit=100&crs=http://www.opengis.net/def/crs/EPSG/0/27700" -H "Accept: application/vnd.ogc.fg+json;compatibility=geojson"` ([link](https://demo.ldproxy.net/zoomstack/collections/airports/items?limit=100&crs=http://www.opengis.net/def/crs/EPSG/0/27700&f=jsonfgc))

**Comment by cportele** [comment]
Meeting 2021-11-29:

* The sprint selected this approach, because it is a media type specific selection, so a media type parameter is more appropriate than, e.g., a general query parameter. 
* When we register the media type, the parameter would need to be defined as part of the registered.
* We agreed to include this approach in the specification.

**Comment by ilkkarinne** [comment]
Would "API should omit the geometry member" mean literally dropping the ```geometry``` member, making the returned object an invalid GeoJSON object, or returning it with a ```null``` value? Requiring/recommending the first option *by default* would seem a bit dangerous to me as it would cause issues with non-FG clients.

**Comment by cportele** [comment]
@ilkkarinne - Thanks. Include as `"geometry": null`, so "omit" is not the correct wording.

**Comment by cportele** [comment]
The spatial geometry has been included in the draft spec. We can close this issue and discuss new issues/comments on the draft.
