### ISSUE TITLE
Proposal: Relationships and links

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#17]
Features can have properties that are relationships with other features or resources like codelists, etc. There are multiple options how to encode such relationships and JSON-FG could provide guidance how to represent such relationships.

Relationships will often be direct properties of the feature, but they may also occur in embedded JSON objects.

Like all other properties, properties that are relationships may have a maximum multiplicity greater than one. That is, the JSON representation may be an array of relationships.

There is not yet a full proposal, but multiple options how to represent relationships and links. It is unclear, if we can or should do more.

https://github.com/opengeospatial/ogc-feat-geo-json/blob/main/proposals/relationships-and-links.adoc

**Comment by cportele** [comment]
Meeting 2021-08-23: 

* The general preference seems to be to not prescribe one approach, but leave the decision to the data provider. Different organisations will prefer different linking patterns. So we would restrict this to examples and guidance, but avoid firm requirements. Clemens will also add text about embedded and/or referenced objects.
* Registering the spatial topological relationships once is a good idea for cases where relationships are pre-computed or are computed on the fly but are presented, because the clients cannot easily compute them. This should be in the IANA register to make the spatial aspects more accessible also for those that do not know OGC or its standards. Clemens will propose definitions.
* Clemens will also contact the O&M group.

**Comment by meastp** [comment]
@cportele I'm interested in this for expressing spatial topological relationships, but the documentation link provided leads to 404 Not Found. Do you have the original document or an update on this?

**Comment by cportele** [comment]
@meastp - Sorry, we need to update all issues after the draft spec is available. This will be done over the next two weeks. 

The content is now part of the draft, see [Annex D](https://docs.ogc.org/DRAFTS/21-045.html#relationships_and_links) and [section E.5](https://docs.ogc.org/DRAFTS/21-045.html#_links).

**Comment by meastp** [comment]
@cportele Thank you for the links :) I like the approach of including links directly in "properties" as this makes it possible to associate information with the link (e.g. spatial topological links from a polygon to the linestrings of which the polygon is composed, could for example contain boundary/ring index and (segment) index as vital information belonging to the link itself).

**Comment by cportele** [comment]
Relationsships and linking is discussed in an informative annex of the draft spec. We can close this issue and discuss new issues/comments on the draft.
