### ISSUE TITLE
Scope the featureType key at the collection level ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogc-feat-geo-json#18]
I am creating this issue so that the SWG can discuss allowing the `featureType` key to also be placed at the collection level.

Right now, the `featureType` key is defined at the feature level so that a server can assert the feature type for a specific feature in a collection.  

Allowing the `featureType` key to be able to exist at the collection level would assert the feature type for all features in the collection.  The rule would be similar to the `coord-ref-sys` key.  That is, if the `featureType` key is present at the collection level then all features in the collection are of that feature type **_UNLESS_** there is a closer-to-scope assertion of the feature type.  

There is also a related issue about how one gets the schema of a specific feature type or list of feature types (see: https://github.com/opengeospatial/ogcapi-features/issues/634).

**Comment by cportele** [comment]
Meeting 2021-10-04: Agreed to also allow a `featureType` key at the feature collection level.

**Comment by cportele** [comment]
`featureType` on the feature collection level is supported in the draft spec.
