### ISSUE TITLE
Use of the term "temporal geometry"

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/ogc-feat-geo-json#31]
I did a search on "temporal geometry". Basically, all the top results have to do with music. For example, Temporal Geometry is a manufacturer of Royalty Free sample libraries for use in film, games, motion graphics and computer based music ...

The next set of "hits" was related to deep learning and facial recognition. 

Yes, "temporal geometry" is used in 19108 and GML. After also searching mathematics and temporal geometry, what the heck is temporal geometry and is this the correct term we should be using? Or is it some strange OGC/ISO twist resulting in things like: A common way to store temporal points in PostGIS is to represent them as geometries of type LINESTRING M and abuse the M dimension to encode timestamps as seconds since 1970-01-01 00:00:00. These time-enhanced geometries, called trajectories, can be validated with the function ST_IsValidTrajectory to verify that the M value is growing from each vertex to the next.

At the very least, the use of the term in JSON-FG should be well defined. Or, perhaps, the correct usage is that time is a property of a geometry?

**Comment by cportele** [comment]
The use of "temporal geometry" is mainly driven by Topic 2 where a CRS can be spatial, temporal or a combination. A geometry in ISO 19107, e.g. a Point or a Curve, is also no longer restricted to spatial axes, but can also include a temporal axis. And - as pointed out - ISO 19108 and GML also use the terminology of geometry and topology for time.

But even if the use would be correct with respect to the OGC baseline, it should not be confusing to readers that are not familiar with the OGC and ISO standards. Maybe we should use "geometry" only for spatial, drop the use of "temporal geometry" and include definitions for the temporal terms/concepts that we use?

**Comment by cportele** [comment]
Meeting 2022-01-22: Agreement to not use "temporal geometry". @cportele will create a PR and also look for other terms that are very "OGCish".

What should we do with "feature"? The term is at least known by everyone that is familiar with GeoJSON.
