### ISSUE TITLE
Avoid the use of start instant + duration

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogc-feat-geo-json#32]
In section 7.2 there is a highlighted Note: 
`ISO 8601 also supports intervals by a duration (a start instant and the duration or
the duration and an end instant). Should this also be supported or does that make parsing just more complex for clients?`
I propose not to do this because IETF RFC 3339 very carefully does not. The RFC only establishes the monotonic ordering of timestamps in a restricted ISO8601 notation. The RFC avoids any hint of differencing two instants to get a duration. The subtraction is not deterministic, at the precision of a second, or perhaps a day, if the calendar algorithms and intercalations (leap seconds, leap days, etc) are not well understood. 
The ordering of the timestamp instants is rigorous providing only one clock is used, thus comparisons (before, after, equal) give proveably correct results.

**Comment by cportele** [comment]
Thank you for highlighting this important aspect. I agree, it would be safer to not support durations.

**Comment by cportele** [comment]
I am reopening this, because we still need a decision in the SWG what to do with the note in the document.

**Comment by cportele** [comment]
Meeting 2022-02-21: We agreed that adding support for duration adds complication that we don't need or want in Part 1. @cportele will remove the highlighted text and then close.
