### ISSUE TITLE
Terminology: TRS or Temporal CRS

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogc-feat-geo-json#34]
In 7.4.1, `temporal CRS: Gregorian` is mentioned. This should read `temporal RS: Gregorian` as `Gregorian` is a calendar, not a Coordinate Reference System, but it is a Temporal Reference System.

**Comment by cportele** [comment]
I think we should reference a temporal CRS. Basically the CRS from [Topic 2 of the OGC Abstract Specifications, Annex E.4.1](https://docs.ogc.org/as/18-005r4/18-005r4.html#118). 

Interestingly there is no such temporal CRS registered by the Naming Authority. There are some temporal CRS that have been registered (see http://www.opengis.net/def/crs/OGC/0/), but no that one from Topic 2. Maybe we should register one? 

We should also check, if the Temporal DWG has discussed registration of temporal CRSs before?

**Comment by chris-little** [comment]
@cportele Most of the temporal CRSs in the Naming Authority register were lodged by the Coverages SWG. Then the Temporal DWG agreed to act as a Quality Assurance board or gate-keeper for the temporal CRSs. It was not envisaged that the Temporal DWG would be the sole owner of temporal CRSs. That could change with the newly revitalised Naming Authority.

I would argue that CRSs and calendars (as in Gregorian) are different things. A CRS has conventional arithmetic, axes, one unit per axis, axis directions. A calendar has unconventional and imprecise arithmetic, multiple units, inconsistency, and an axis with direction.  If a Gregorian Temporal Reference System is registered, there needs to be a clear statement of the algorithms (e.g. no leap seconds) and an unambiguous notation so that people do not infer wrongly that it is another TRS (e.g. with leap seconds, or without leap days, etc). Unfortunately, the ISO8601 notation does not give us that facility, but a reference to the NA would.

I think there are separate 'branches' of `crs` which coulc include temporal, and `trs` which could include calendars.

**Comment by cportele** [comment]
@chris-little - I think we need registered temporal CRS in OGC that also clarify the arithmetic etc., not "just" the calendar. In most cases positions in time should be associated with such a CRS. Just like for spatial geometries where we also always reference a CRS, even if computation of length or area are not required.
