### ISSUE TITLE
Define what is "primary geometry"

### ISSUE THREAD

**Issue by jratike80** [opengeospatial/ogc-feat-geo-json#38]
Term "primary geometry" is used frequently in the draft without a definition about what it means. It may make readers to believe that there can also be "secondary geometries" or "additional geometries" but all that connects to such things is in the comment:

> JSON-FG will not support multiple geometries per feature (note that multiple geometries can be included inside the "properties" member) or any hints about the semantics of the geometry. The latter could potentially be addressed using JSON-LD contexts where this is important.

1. Do we need "primary geometry" at all, or could is be just "geometry"?
2. If "primary geometry" is used, it would be good to add it into the glossary, and write clearly that only one geometry is allowed in "geometry" and "where", and additional geometries must be inserted into "properties".

**Comment by cportele** [comment]
Agreed, we need to be clearer about the terms and concepts. On the first question, I think that we need to be clear that while most features in datasets have a single geometry, in general a feature can have multiple geometry properties and that in such cases it is the decision of the creator of the data, which of the properties to encode in "geometry"/"where". It seems easiest to have a term ("primary geometry" or something else).

**Comment by cportele** [comment]
Meeting 2022-02-07: Add "primary geometry" to terms and definition with a note that explains the context with respect to multiple geometry properties. @cportele will create a PR.
