### ISSUE TITLE
Require UTC?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#40]
GeoPackage, the next versions of CDB and the Common Query Language will only support UTC as a time zone in literal values. Should JSON-FG follow this approach?

See https://docs.ogc.org/DRAFTS/21-045.html#_instants

**Comment by pvretano** [comment]
@cportele yes!

**Comment by cportele** [comment]
Meeting 2022-02-21: We agreed to make the change. It makes processing of the documents easier and is consistent with the other related standards. @cportele will update the document and close the issue.
