### ISSUE TITLE
Potential ambiguity related to 'coordRefSys' naming

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ogc-feat-geo-json#46]
My understanding of the draft spec is that 'coordRefSys' only applies to the 'place' member, and to the potential 'geometry'. However this is far from obvious to someone who doesn't read the spec closely (who reads specs? :-)). I would suggest renaming 'coordRefSys' to 'placeCoordRefSys' or something else that avoids any ambiguity.

**Comment by cportele** [comment]
Meeting 2022-04-04: `placeCoordRefSys` is also not really correct or intuitive as the `coordRefSys` member can also be included in a geometry object, including those in `properties`. At a minimum we need to be clearer in the spec, but how can we make it intuitively clear and still correct. One approach can be more visible examples, also more prominently in the repo. Let's try this and then evaluate, if this is intuitive enough.

**Comment by pvretano** [comment]
I reviewed the document and the very first reference to `coordRefSys` says:
''''
A new key "coordRefSys" is defined and can be used to assert the CRS of a JSON-FG geometry object at the collection, feature, or value levels.
''''
This point, that the `coordRefSys` key indicates the CRS of a JSON-FG geometry object, is made in several subsequent references so I think the point is clear that coordRefSys does not apply to the GeoJSON `geometry` member.
Two point might, however, be in order.
1. Explicitly state that the `coordRefSys` member does not apply to the GeoJSON `geometry` member.
2. To @cportele point about geometry object in the `properties` section.  I could not find that mentioned in the specification so we want to add that clarficiation.
