### ISSUE TITLE
Requirement 9   /req/core/place confusing or wrong

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ogc-feat-geo-json#48]
The title of the paragraph is " No GeoJSON geometry in "place"  and the requirement reads "If the "place" member in any JSON-FG feature in the JSON document is not null and the geometry type (member "type") is one of "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon" or "MultiPolygon", the CRS SHALL not use WGS84 longitude/latitude as the first two coordinate axes."
The requirement text doesn't match the title.

**Comment by cportele** [comment]
Meeting 2022-04-04: Yes, good point. This will be fixed.
