### ISSUE TITLE
Name of the standard

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#5]
The current name of the standard is "OGC Features and Geometries JSON", which describes the scope of the standard, but is quite long. We will need at least a shorter form that can be used to reference the standard.

OGC staff is working on a proposal.

**Comment by jeffharrison** [comment]
"JSON-FG" has potential I'd think...

**Comment by cportele** [comment]
Meeting 2022-01-24: We will continue to use JSON-FG, it seems to be used in references to this work. We can close this issue.
