### ISSUE TITLE
Placeholders in the document

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#52]
The following placeholders (that are not referenced by any other open issue) are left in the document after the edits in branch `cp-edits` are merged. To be discussed, but we probably should resolve all of them before tagging the first draft release.

* [x] Add section "Abstract"
* [x] Add an Annex with examples how future parts or communities can extend the schemas
* [x] Add figure(s) illustrating polyhedra.
* [x] Add figure(s) illustrating point extrusion.
* [x] Add figure(s) illustrating a ribbon.
* [x] Add figure(s) illustrating a polygon extrusion.
* [x] Add more examples, e.g. of a homogenous feature collection.

**Comment by cportele** [comment]
Meeting 2022-05-30: These edits are all purely editorial and can be added directly to the master branch so that they end up in the HTML document.

**Comment by lvdbrink** [comment]
I contacted 3DGeoInfo at Delft University. Balázs Dukai came up with two examples for a point and a line extrusion, they are not real life examples unfortunately and he was not able to visualize them. But for what it's worth here's the code: 

`{
    "type": "Feature",
    "id": "pylon1",
    "featureType": "pylon",
    "time": {
       "interval": [ "2022-07-12T16:47:18Z", null ]
    },
    "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/7415",
    "geometry": {
        "type": "Prism",
        "base": {
            "type": "Point",
            "coordinates": [ 81220.15, 455113.71]
        },
        "lower": 2.02,
        "upper": 8.02
    },
    "properties": null
 }`

and 

`{
    "type": "Feature",
    "id": "fence1",
    "featureType": "fence",
    "time": {
        "interval": [
            "2022-07-12T16:55:18Z",
            null
        ]
    },
    "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/7415",
    "geometry": {
        "type": "Prism",
        "base": {
            "type": "LineString",
            "coordinates": [
                [ 81220.15, 455113.71 ],
                [ 81223.15, 455116.71 ]
            ]
        },
        "lower": 2.02,
        "upper": 3.22
    },
    "properties": null
}`

**Comment by cportele** [comment]
Closed by #57 as completed
