### ISSUE TITLE
Publish schemas on https://beta.schemas.opengis.net/

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogc-feat-geo-json#53]
Once tagged, the JSON schemas of version 0.1 should be published at https://beta.schemas.opengis.net/json-fg/.

**Comment by cportele** [comment]
Meeting 2022-07-25: @cportele to prepare the JSON schemas as a zip file after the release.

**Comment by cportele** [comment]
@ghobona - After resolving #65:

Could you publish the JSON schemas at https://github.com/opengeospatial/ogc-feat-geo-json/releases/download/v0.1.1/json-fg-schemas-v0.1.1.zip at https://beta.schemas.opengis.net/json-fg/ ? 

Thank you!

**Comment by cportele** [comment]
@ghobona - A reminder to publish the JSON Schemas on the OGC beta site: https://github.com/opengeospatial/ogc-feat-geo-json/issues/53#issuecomment-1252539522. Let me know, if you have any questions. Thank you.

**Comment by ghobona** [comment]
@cportele @jechterhoff A ticket has now been created for the Infrastructure Office to publish the beta schemas.

**Comment by jechterhoff** [comment]
@ghobona Can you give an update on this issue? We'd really like to use the draft schemas once available on https://beta.schemas.opengis.net/json-fg/

**Comment by ghobona** [comment]
@jechterhoff The schemas have just been published.

**Comment by ghobona** [comment]
@cportele Ok, thanks for spotting the issue.

Cc: @kstegemoller

**Comment by kstegemoller** [comment]
@cportele @jechterhoff 

While the policy I am following is based on the XML schema policy described at 
https://portal.ogc.org/public_ogc/directives/directives.php#22 ,
I do believe a version is important. 

This very issue contains a link to an issue https://github.com/opengeospatial/ogc-feat-geo-json/issues/65
which needed to change the schema.  Why not plan for the "worst" case allowing versioning of the schema and never needing to use it, rather than to not have a version and then possibly having a breaking change in a future revision. 

> There are now two options:
> 
>     * You move the schemas to https://beta.schemas.opengis.net/json-fg.
> 
>     * We create a version 0.1.2 and update the schemas and the document to include a version number in the path. https://beta.schemas.opengis.net/json-fg/0.1.1 would be removed and the schemas would be published at https://beta.schemas.opengis.net/json-fg/0.1.2.
> 
> 
> I would prefer the first option. If that does not work for some reason, let me know and I will prepare a PR for version 0.1.2.

The SWG may choose to post without a version but it seems to me that adding a Major.Minor version allows for the most flexibility in the future.   Please, let me know which way you choose.

Thanks!

**Comment by cportele** [comment]
@kstegemoller 

It was a deliberate decision to exclude the version number, see https://docs.ogc.org/DRAFTS/21-045.html#_extensibility, including:

> The JSON schemas are designed to support extensions. JSON-FG documents that include extensions will still validate against the JSON-FG schemas.
>
> The "$id" member of the schemas does not include information about the version of the Standard or the part of the JSON-FG standard. Future revisions of this Standard or additional parts of JSON-FG will update and extend the JSON-FG schemas. Any change will not invalidate existing JSON-FG documents.

Of course, before a version 1.0 is approved, there can always by definition be breaking changes to the schemas, but it is the goal to extend the schemas only in ways that maintain backwards compatibility (with JSON Schemas we fortunately don't have the same issues as with XML Schemas).

If the version number should be included, it would be just the major.minor (i.e., 0.1, not 0.1.1) and a bugfix would always replace the previous version.

Thanks, Clemens

**Comment by ghobona** [comment]
@cportele How about adding the version number as a comment?

Alternatively, the version number could be added as a statement in the description. 

https://json-schema.org/understanding-json-schema/reference/generic.html

An equivalent of a README.md file stating the version number (placed in the root folder) would also be needed if the URLs to the JSON Schema files do not have version number.

**Comment by cportele** [comment]
@ghobona Good point.

I will add the version in the description (comments are only for schema editors, not for users of the schemas, at least this is what JSON Schema states on the page you have linked) and add a README.md file. Stay tuned...

**Comment by ogcportal** [comment]
@cportele As there is no official version policy for json, you (SWG) may make the final call regarding versioned URL.  Just let me know which way to proceed.  I do agree the description/comments/README are only for editors/information and not for the user/consumer of the schema.

**Comment by kstegemoller** [comment]
@cportele As there is no official version policy for json, you (SWG) may make the final call regarding versioned URL. Just let me know which way to proceed. I do agree the description/comments/README are only for editors/information and not for the user/consumer of the schema.

**Comment by cportele** [comment]
@kstegemoller - Thanks, the schema package has been updated (each schema file includes a description that includes the version number, a README.md has been added based on the style used in schemas.opengis.net and with information about the approach). 

https://github.com/opengeospatial/ogc-feat-geo-json/releases/download/v0.1.1/json-fg-schemas-v0.1.1.zip

Let me know, if you have any questions or concerns. Thanks a lot!

**Comment by kstegemoller** [comment]
@cportele 
json-fg v0.1.1 schemas posted to https://beta.schemas.opengis.net/json-fg/

**Comment by cportele** [comment]
Great, thanks, @kstegemoller
