### ISSUE TITLE
What is a CustomGeometry?

### ISSUE THREAD

**Issue by balazsdukai** [opengeospatial/ogc-feat-geo-json#73]
Related to #72 

According to the schema, a CustomGeometry only requires a `type`.
https://github.com/opengeospatial/ogc-feat-geo-json/blob/6e27bc226f8da975d691a064f44e3e3fc150b941/core/schemas/geometry-objects.json#L6-L30

What is the a CustomGeometry meant for? How to handle it in a client?

**Comment by cportele** [comment]
Meeting 2022-10-31: @cportele to draft a PR to add an explanation to the extension discussion.
