### ISSUE TITLE
Shouldn't "C.3. Toronto City Hall" example refer to CRS84h ?

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ogc-feat-geo-json#78]
https://docs.ogc.org/DRAFTS/21-045.html#_toronto_city_hall has ``"coordRefSys": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"``. Given that lower and upper are used, shouldn't coordRefSys point to http://www.opengis.net/def/crs/OGC/0/CRS84h instead ?

**Comment by cportele** [comment]
Yes, I agree. For prisms the CRS should be a 3D CRS (compund or not).
