### ISSUE TITLE
Object to Object linking

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/ogc-feat-geo-json#8]
We’re looking for a common linking pattern to be reused in OGC encoding, specifically O&M, where we have multiple objects interlinked. Is there one way of defining links that works with 

- GeoJSON
- JSON
- JSON-LD

How would an encoding be recommended pertaining to object to object links? How do we then integrate this with the requirements posed by the various APIs?

In name of the O&M SWG

**Comment by cportele** [comment]
See also #17 and https://github.com/opengeospatial/ogc-feat-geo-json/blob/main/proposals/relationships-and-links.adoc.

**Comment by cportele** [comment]
This aspect is discussed in the draft spec (in an informative annex). We can close this issue and discuss new issues/comments on the draft.
